import { afterEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { NetworkLesson } from './NetworkLesson'
import { createNetwork } from './network'

afterEach(cleanup)

describe('network lesson interactions', () => {
  it('runs the full numeric fixture in separate phases without implicit updates', () => {
    render(<NetworkLesson kind="linear" />)
    expect(screen.getByTestId('network-prediction')).toHaveTextContent('—')
    expect(screen.getByRole('button', { name: '3 Backward' })).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: '1 Forward' }))
    expect(screen.getByTestId('network-prediction')).toHaveTextContent('7')
    expect(screen.getByTestId('network-loss')).toHaveTextContent('—')
    fireEvent.click(screen.getByRole('button', { name: '2 Loss' }))
    expect(screen.getByTestId('network-loss')).toHaveTextContent('4')
    fireEvent.click(screen.getByRole('button', { name: '3 Backward' }))
    expect(screen.getByLabelText('Weight w')).toHaveValue(3)
    fireEvent.click(screen.getByRole('button', { name: 'Inspect layer 1 neuron 1' }))
    expect(screen.getByRole('cell', { name: '-8' })).toBeVisible()
    expect(screen.getByRole('cell', { name: '-4' })).toBeVisible()
    fireEvent.click(screen.getByRole('button', { name: '4 Update parameters' }))
    expect(screen.getByLabelText('Weight w')).toHaveValue(3.4)
    expect(screen.getByLabelText('Bias b')).toHaveValue(1.2)
    expect(screen.getByTestId('network-prediction')).toHaveTextContent('8')
    expect(screen.getByTestId('network-loss')).toHaveTextContent('1')
    expect(screen.getByRole('button', { name: '4 Update parameters' })).toBeDisabled()
  })

  it('opens neighboring modules independently and preserves state across breadcrumbs and arithmetic', () => {
    render(<NetworkLesson kind="small-network" />)
    fireEvent.click(screen.getByRole('button', { name: '1 Forward' }))
    fireEvent.click(screen.getByRole('button', { name: /Hidden layer 1/ }))
    fireEvent.click(screen.getByRole('button', { name: /Output layer 2/ }))
    expect(screen.getByRole('button', { name: /Hidden layer 1/ })).toHaveAttribute('aria-expanded', 'true')
    expect(screen.getByRole('button', { name: /Output layer 2/ })).toHaveAttribute('aria-expanded', 'true')
    fireEvent.click(screen.getByRole('button', { name: 'Inspect layer 1 neuron 2' }))
    fireEvent.click(screen.getByRole('button', { name: 'Open arithmetic' }))
    expect(screen.getByText(/-0.5 \+ 2 \+ \(0\) = 1.5/)).toBeVisible()
    fireEvent.click(screen.getByRole('button', { name: 'Network' }))
    fireEvent.click(screen.getByRole('button', { name: /Output layer 2/ }))
    expect(screen.getByRole('button', { name: /Hidden layer 1/ })).toHaveAttribute('aria-expanded', 'true')
    expect(screen.getByTestId('network-prediction')).toHaveTextContent('1')
    fireEvent.click(screen.getByRole('button', { name: 'Inspect layer 1 neuron 2' }))
    expect(screen.getByLabelText('Layer 1 neuron 2 weight 1')).toHaveValue(-.5)
  })

  it('invalidates stale values after edits and keeps the activation graph linked', () => {
    render(<NetworkLesson kind="neuron" />)
    fireEvent.click(screen.getByRole('button', { name: '1 Forward' }))
    fireEvent.change(screen.getByLabelText('Input x1'), { target: { value: '-2' } })
    expect(screen.getByTestId('network-prediction')).toHaveTextContent('—')
    expect(screen.getByRole('button', { name: '2 Loss' })).toBeDisabled()
    fireEvent.change(screen.getByLabelText('Activation'), { target: { value: 'relu' } })
    fireEvent.click(screen.getByRole('button', { name: '1 Forward' }))
    expect(screen.getByTestId('network-prediction')).toHaveTextContent('0')
    fireEvent.click(screen.getByRole('button', { name: 'Inspect layer 1 neuron 1' }))
    expect(screen.getByRole('img', { name: 'Selected neuron activation response graph' })).toBeVisible()
  })

  it('selects plotted examples for tracing and protects validation from updates', () => {
    render(<NetworkLesson kind="linear" />)
    fireEvent.click(screen.getByRole('button', { name: /^point-1, validation,/ }))
    expect(screen.getByTestId('network-prediction')).toHaveTextContent('—')
    fireEvent.click(screen.getByRole('button', { name: '1 Forward' }))
    fireEvent.click(screen.getByRole('button', { name: '2 Loss' }))
    fireEvent.click(screen.getByRole('button', { name: '3 Backward' }))
    expect(screen.getByRole('button', { name: '4 Update parameters' })).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: 'Next visible component' }))
    expect(screen.getByLabelText('Weight w')).toHaveValue(3)
  })

  it('trains a fixed budget, records both losses, and reset preserves the data', async () => {
    render(<NetworkLesson kind="playground" />)
    fireEvent.click(screen.getByRole('button', { name: 'Train 20 epochs' }))
    await waitFor(() => expect(screen.getByRole('button', { name: 'Train 20 epochs' })).toBeEnabled())
    expect(screen.getByText('20', { selector: 'strong' })).toBeVisible()
    expect(screen.getByRole('status')).toHaveTextContent('Validation examples were never used for updates')
    fireEvent.click(screen.getByRole('button', { name: 'Save comparison' }))
    expect(screen.getByText('Run 1')).toBeVisible()
    fireEvent.click(screen.getByRole('button', { name: 'Reset parameters' }))
    expect(screen.getByText('Data seed 137')).toBeVisible()
    expect(screen.getByTestId('network-prediction')).toHaveTextContent('—')
    fireEvent.change(screen.getByLabelText('Hidden layer 1 width'), { target: { value: '6' } })
    expect(screen.getByText('Data seed 137')).toBeVisible()
    expect(screen.getByRole('button', { name: 'Inspect layer 1 neuron 6' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Undo' }))
    expect(screen.queryByRole('button', { name: 'Inspect layer 1 neuron 6' })).not.toBeInTheDocument()
  })

  it('restores parameters, inputs and view state while independently recomputing cached output', async () => {
    const { container } = render(<NetworkLesson kind="linear" />)
    const model = createNetwork('linear'); model.layers[0].weights = [3.4]; model.layers[0].biases = [1.2]
    const file = new File(['{}'], 'saved.json', { type: 'application/json' })
    Object.defineProperty(file, 'text', { value: async () => JSON.stringify({ kind: 'backprop-network-experiment', version: 1, state: { model, example: { id: 'custom', x: [2], y: 9, split: 'train' }, phase: 'backward', recorded: { calculation: { prediction: 9999 } }, epoch: 0, losses: [], expanded: ['layer-0'], selectedLayer: 0, selectedNeuron: 0, detail: 'arithmetic', visibleStep: 0 }, view: { showGradients: true } }) })
    fireEvent.change(container.querySelector('input[type=file]')!, { target: { files: [file] } })
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Experiment restored'))
    expect(screen.getByTestId('network-prediction')).toHaveTextContent('8')
    expect(screen.getByTestId('network-loss')).toHaveTextContent('1')
    expect(screen.getByRole('cell', { name: '-4' })).toBeVisible()
    expect(screen.getByLabelText('Weight w')).toHaveValue(3.4)
    expect(screen.getByRole('button', { name: /Output layer 1/ })).toHaveAttribute('aria-expanded', 'true')
  })

  it('passes the current graph with full-square loss to the preserved builder', () => {
    const onBuilder = vi.fn()
    render(<NetworkLesson kind="linear" onBuilder={onBuilder} />)
    fireEvent.change(screen.getByLabelText('Weight w'), { target: { value: '4' } })
    fireEvent.click(screen.getByRole('button', { name: 'Open in graph builder' }))
    expect(onBuilder).toHaveBeenCalledOnce()
    expect(onBuilder.mock.calls[0][0].nodes.find((node: { id: string }) => node.id === 'layer-0/weight-0-0').params.value).toBe(4)
    expect(onBuilder.mock.calls[0][0].nodes.find((node: { id: string }) => node.id === 'loss').params.loss).toBe('mse')
  })
})
