import { fireEvent, render, screen, within, waitFor } from '@testing-library/react'
import { afterAll, beforeAll, afterEach, describe, expect, it, vi } from 'vitest'
import { TransformerLesson } from './TransformerLesson'
import * as exploration from './exploration'
import { DECODER_CONFIG, decoderForward, getCheckpoint, loadCheckpoint, sampleToken } from './decoder'
import { numberLabel } from './format'

const matrix = (name: string) => screen.getByRole('table', { name })
const matrixValues = (name: string) => within(matrix(name)).getAllByRole('button').map(button => button.textContent)
const click = (name: string | RegExp) => fireEvent.click(screen.getByRole('button', { name }))
const open = (name: RegExp) => {
  const button = screen.getByRole('button', { name })
  if (button.getAttribute('aria-expanded') !== 'true') fireEvent.click(button)
  return button.closest('section')!
}
const renderLesson = (kind: Parameters<typeof TransformerLesson>[0]['kind']) => {
  render(<TransformerLesson kind={kind} />)
  const controls = screen.queryByRole('button', { name: 'Show controls' })
  if (controls) fireEvent.click(controls)
}
const saveSpy = () => vi.spyOn(exploration, 'downloadExploration').mockImplementation(() => {})
const originalScroll = Object.getOwnPropertyDescriptor(Element.prototype, 'scrollIntoView')
beforeAll(() => Object.defineProperty(Element.prototype, 'scrollIntoView', { configurable: true, value: vi.fn() }))
afterAll(() => {
  if (originalScroll) Object.defineProperty(Element.prototype, 'scrollIntoView', originalScroll)
  else Reflect.deleteProperty(Element.prototype, 'scrollIntoView')
})
afterEach(() => vi.restoreAllMocks())

describe('rendered local transformer explorations', () => {
  it('renders stable softmax arithmetic and invalidates old results after editing scores', () => {
    renderLesson('probabilities')
    const distribution = screen.getByLabelText('Probability distribution').textContent
    expect(distribution).toContain('9.00%'); expect(distribution).toContain('24.47%'); expect(distribution).toContain('66.52%')
    expect(screen.getByText('Total probability').closest('tr')).toHaveTextContent('1')
    click('Add 10 to all scores')
    expect(screen.getByRole('status')).toHaveTextContent('invalidated')
    expect(screen.queryByLabelText('Probability distribution')).not.toBeInTheDocument()
    click('Run forward')
    expect(screen.getByLabelText('Probability distribution').textContent).toBe(distribution)
    expect(screen.getByRole('status')).toHaveTextContent('No parameters were updated')
    fireEvent.click(screen.getByRole('checkbox', { name: 'Formulas' }))
    fireEvent.click(screen.getByRole('checkbox', { name: 'Python reference' }))
    expect(screen.getByText(/pᵢ = exp/)).toBeInTheDocument()
    expect(screen.getByText(/shifted = scores - max/)).toBeInTheDocument()
  })

  it('recalculates the V intervention while preserving Q, K and attention weights, and resets exactly', () => {
    renderLesson('attention')
    const weights = matrixValues('Attention weights'), queries = matrixValues('Q · queries'), keys = matrixValues('K · keys')
    expect(weights).toEqual(['0.25', '0.5', '0.25'])
    expect(matrixValues('Weighted values · output')).toEqual(['1', '1.5'])
    click('Intervene: middle V → [0, 4]')
    expect(screen.getByRole('status')).toHaveTextContent('invalidated')
    expect(screen.queryByRole('table', { name: 'Weighted values · output' })).not.toBeInTheDocument()
    click('Run forward')
    expect(matrixValues('Attention weights')).toEqual(weights)
    expect(matrixValues('Q · queries')).toEqual(queries); expect(matrixValues('K · keys')).toEqual(keys)
    expect(matrixValues('Weighted values · output')).toEqual(['1', '2.5'])
    click('Reset V intervention'); click('Run forward')
    expect(matrixValues('Weighted values · output')).toEqual(['1', '1.5'])
  })

  it('sets both middle-value coordinates during intervention, even after a manual V edit', () => {
    renderLesson('attention')
    fireEvent.change(screen.getByRole('spinbutton', { name: 'V row 1 coordinate 0' }), { target: { value: '3' } })
    click('Intervene: middle V → [0, 4]'); click('Run forward')
    expect(matrixValues('V · values')).toEqual(['2', '0', '0', '4', '2', '2'])
    expect(screen.getByRole('spinbutton', { name: 'V row 1 coordinate 0' })).toBeDisabled()
    click('Reset V intervention'); click('Run forward')
    expect(matrixValues('V · values')[2]).toBe('3')
  })

  it('exposes causal exclusions and preserves earlier output rows after a future-value edit', () => {
    renderLesson('causal')
    const output = matrixValues('Weighted values · output')
    expect(matrixValues('After causal mask')).toEqual(['0.7071', 'masked', 'masked', '0', '0.7071', 'masked', '0.7071', '0.7071', '1.4142'])
    fireEvent.click(within(matrix('Attention weights')).getByRole('button', { name: /^Attention weights row 0 column 2:/ }))
    expect(screen.getByText(/Future position: excluded/)).toBeInTheDocument()
    fireEvent.change(screen.getByRole('spinbutton', { name: 'V row 2 coordinate 1' }), { target: { value: '9' } })
    click('Run forward')
    expect(matrixValues('Weighted values · output').slice(0, 4)).toEqual(output.slice(0, 4))
    expect(matrixValues('Weighted values · output').slice(4)).not.toEqual(output.slice(4))
  })

  it('traces token embeddings, an attention cell and a feedforward neuron through the actual checkpoint', () => {
    renderLesson('decoder')
    const trace = decoderForward(loadCheckpoint(getCheckpoint('trained')), [0, 1, 2])
    open(/^Token \+ position embeddings/)
    expect(matrixValues('Model input')).toEqual(trace.input.data.map(numberLabel))
    fireEvent.click(screen.getByRole('button', { name: /^red\s*position 1/ }))
    expect(screen.getByRole('button', { name: /^red\s*position 1/ })).toHaveAttribute('aria-pressed', 'true')
    open(/^Transformer block 1/); open(/^Multi-head causal attention/); const head = open(/^Attention head 1/)
    expect(matrixValues('Attention weights')).toEqual(trace.blocks[0].heads[0].weights.data.map(numberLabel))
    fireEvent.click(within(head).getByRole('button', { name: /^Attention weights row 1 column 1:/ }))
    expect(within(head).getByText('Query 1 → key 1')).toBeInTheDocument()
    open(/^Feedforward network/); open(/^Hidden layer · 16 neurons/)
    click('Inspect hidden neuron 3')
    const card = screen.getByText('Neuron 3 → weighted sum → individual arithmetic').closest('.arithmetic-card')!
    const rows = within(card as HTMLElement).getAllByRole('row').slice(1), parameters = getCheckpoint('trained').parameters
    expect(rows).toHaveLength(8)
    rows.forEach((row, i) => {
      const cells = within(row).getAllByRole('cell'), input = trace.blocks[0].norm2.data[8 + i], weight = parameters['blocks.0.ff1'].data[i * 16 + 3]
      expect(cells.map(cell => cell.textContent)).toEqual([numberLabel(input), numberLabel(weight), numberLabel(input * weight)])
    })
    expect(within(card as HTMLElement).getByText(/Sum of products/)).toHaveTextContent(numberLabel(trace.blocks[0].ffPre.data[16 + 3]))
    expect(screen.getByRole('button', { name: /^Transformer block 2/ })).toHaveAttribute('aria-expanded', 'false')
  })

  it('preserves values, parameter identities and selected attention cells through closing, reopening and zoom', () => {
    const save = saveSpy()
    renderLesson('decoder')
    open(/^Transformer block 1/); open(/^Multi-head causal attention/); open(/^Attention head 1/)
    fireEvent.click(screen.getByRole('button', { name: /^Attention weights row 1 column 2:/ }))
    const weights = matrixValues('Attention weights'), baseLogits = matrixValues('Fixed prompt base logits')
    click('Save state'); const before = structuredClone(save.mock.calls.at(-1)![0])
    click(/^Attention head 1/); open(/^Attention head 1/)
    expect(screen.getByText('Query 1 → key 2')).toBeInTheDocument()
    click(/^Transformer block 1/); open(/^Transformer block 1/)
    expect(screen.getByText('Query 1 → key 2')).toBeInTheDocument()
    click('Zoom in'); click('Zoom out'); click('Fit view'); click('↑ Up a level')
    expect(matrixValues('Attention weights')).toEqual(weights)
    expect(matrixValues('Fixed prompt base logits')).toEqual(baseLogits)
    click('Save state'); const after = save.mock.calls.at(-1)![0]
    expect(after.state.overrides).toEqual(before.state.overrides)
    expect(after.state.ids).toEqual(before.state.ids)
    expect(after.state.checkpoint).toBe(before.state.checkpoint)
    expect(after.state.selectedKeys).toEqual(before.state.selectedKeys)
  })

  it('steps through scores, distribution, choice and append without changing model parameters', () => {
    const save = saveSpy()
    renderLesson('decoder')
    click('Save state'); const before = structuredClone(save.mock.calls.at(-1)![0]), logits = matrixValues('Fixed prompt base logits')
    expect(screen.getByRole('button', { name: '3. Choose token' })).toBeDisabled()
    expect(screen.getByRole('button', { name: '4. Append token' })).toBeDisabled()
    fireEvent.change(screen.getByRole('combobox', { name: 'Selection' }), { target: { value: 'sample' } })
    fireEvent.change(screen.getByRole('spinbutton', { name: 'Sampling temperature' }), { target: { value: '0.7' } })
    fireEvent.change(screen.getByRole('combobox', { name: 'Top-k' }), { target: { value: '1' } })
    expect(matrixValues('Fixed prompt base logits')).toEqual(logits)
    click('2. Form distribution')
    expect(screen.getByLabelText('Probability distribution')).toHaveTextContent('blue100.00%')
    click('3. Choose token')
    expect(screen.getByText(/Append it to make the next prompt/)).toHaveTextContent('Selected blue')
    expect(matrixValues('Fixed prompt base logits')).toEqual(logits)
    click('Save state'); const chosen = save.mock.calls.at(-1)![0]
    expect(chosen.state.overrides).toEqual(before.state.overrides); expect(chosen.state.checkpoint).toBe(before.state.checkpoint)
    expect(chosen.state.ids).toEqual(before.state.ids)
    expect(chosen.state.seed).not.toBe(before.state.seed)
    click('4. Append token')
    expect(screen.getByRole('combobox', { name: 'Token at position 3' })).toHaveValue('3')
    expect(screen.getByRole('status')).toHaveTextContent('invalidated')
    expect(screen.queryByRole('table', { name: 'Fixed prompt base logits' })).not.toBeInTheDocument()
    click('1. Calculate scores'); click('2. Form distribution'); click('3. Choose token')
    expect(screen.getByText(/Append it to make the next prompt/)).toHaveTextContent('Selected red')
    click('Save state'); const after = save.mock.calls.at(-1)![0]
    expect(after.state.overrides).toEqual(before.state.overrides); expect(after.state.checkpoint).toBe(before.state.checkpoint)
  })

  it('navigates actual ancestor breadcrumbs and steps into a block without recalculating', () => {
    renderLesson('decoder')
    const logits = matrixValues('Fixed prompt base logits')
    open(/^Transformer block 1/); click('Step inside'); click('Step inside')
    let crumbs = within(screen.getByRole('navigation', { name: 'Model breadcrumbs' }))
    expect(crumbs.getAllByRole('button').map(button => button.textContent)).toEqual(['A complete miniature decoder', 'Block 1', 'Attention', 'Head 1'])
    click('↑ Up a level')
    crumbs = within(screen.getByRole('navigation', { name: 'Model breadcrumbs' }))
    expect(crumbs.getByRole('button', { name: 'Attention' })).toHaveAttribute('aria-current', 'location')
    fireEvent.click(crumbs.getByRole('button', { name: 'Block 1' }))
    expect(within(screen.getByRole('navigation', { name: 'Model breadcrumbs' })).getByRole('button', { name: 'Block 1' })).toHaveAttribute('aria-current', 'location')
    expect(matrixValues('Fixed prompt base logits')).toEqual(logits)
  })

  it('invalidates parameter edits, stores the exact override, and undo restores original values', () => {
    const save = saveSpy()
    renderLesson('decoder')
    const baseline = matrixValues('Fixed prompt base logits')
    fireEvent.click(screen.getByText('Learned parameters & checkpoint evidence'))
    fireEvent.change(screen.getByLabelText('Parameter identity'), { target: { value: 'unembedding' } })
    const value = getCheckpoint('trained').parameters.unembedding.data[0] + 0.5
    fireEvent.change(screen.getByLabelText('Learned parameter value'), { target: { value: String(value) } })
    expect(screen.getByRole('status')).toHaveTextContent('invalidated')
    expect(screen.queryByRole('table', { name: 'Fixed prompt base logits' })).not.toBeInTheDocument()
    click('Run forward')
    expect(matrixValues('Fixed prompt base logits')).not.toEqual(baseline)
    click('Save state')
    expect(save.mock.calls.at(-1)![0].state.overrides.unembedding[0]).toBe(value)
    click('Undo exploration edit')
    expect(matrixValues('Fixed prompt base logits')).toEqual(baseline)
    expect(screen.getByLabelText('Learned parameter value')).toHaveValue(getCheckpoint('trained').parameters.unembedding.data[0])
  })

  it('imports an already-chosen sampled token and resumes appending without consuming another random draw', async () => {
    const save = saveSpy()
    renderLesson('decoder')
    fireEvent.change(screen.getByRole('combobox', { name: 'Parameters' }), { target: { value: 'untrained' } })
    fireEvent.change(screen.getByRole('combobox', { name: 'Selection' }), { target: { value: 'sample' } })
    fireEvent.change(screen.getByRole('spinbutton', { name: 'Sampling temperature' }), { target: { value: '2' } })
    click('1. Calculate scores'); click('2. Form distribution'); click('3. Choose token'); click('Save state')
    const saved = structuredClone(save.mock.calls.at(-1)![0]), chosen = saved.execution!.choice!
    expect(saved.execution).toMatchObject({ generationPhase: 'chosen', current: true })
    expect(saved.state.seed).not.toBe(42)
    const recordedLogits = matrixValues('Fixed prompt base logits')
    click('4. Append token'); click('1. Calculate scores'); click('2. Form distribution'); click('3. Choose token')
    fireEvent.change(screen.getByLabelText('Import exploration'), { target: { files: [{ text: async () => JSON.stringify(saved) }] } })
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('view restored'))
    expect(screen.getByText(/Append it to make the next prompt/)).toHaveTextContent('Selected ' + DECODER_CONFIG.vocab[chosen])
    expect(screen.getByRole('button', { name: '4. Append token' })).toBeEnabled()
    expect(screen.getByRole('button', { name: '3. Choose token' })).toBeDisabled()
    expect(matrixValues('Fixed prompt base logits')).toEqual(recordedLogits)
    click('Save state'); expect(save.mock.calls.at(-1)![0]).toEqual(saved)
    click('4. Append token')
    expect(screen.getByRole('combobox', { name: 'Token at position 3' })).toHaveValue(String(chosen))
    click('Save state'); expect(save.mock.calls.at(-1)![0].state.seed).toBe(saved.state.seed)
    const nextIds = [...saved.state.ids, chosen], nextLogits = decoderForward(loadCheckpoint(getCheckpoint('untrained')), nextIds).logits.data.slice(-5)
    const expected = sampleToken(nextLogits, { mode: 'sample', temperature: saved.state.temperature, topK: saved.state.topK, seed: saved.state.seed })
    click('1. Calculate scores'); click('2. Form distribution'); click('3. Choose token'); click('Save state')
    const resumed = save.mock.calls.at(-1)![0]
    expect(resumed.execution!.choice).toBe(expected.token)
    expect(resumed.state.seed).toBe(expected.seed)
    expect(resumed.state.ids).toEqual(nextIds)
    expect(resumed.state.overrides).toEqual(saved.state.overrides)
  })

  it('restores a saved comparison and imports the exact saved selection, inputs and overrides', async () => {
    const save = saveSpy()
    renderLesson('decoder')
    const initial = matrixValues('Fixed prompt base logits')
    click('Keep comparison')
    fireEvent.change(screen.getByRole('combobox', { name: 'Token at position 2' }), { target: { value: '3' } }); click('Run forward')
    expect(matrixValues('Fixed prompt base logits')).not.toEqual(initial)
    click('Restore')
    expect(matrixValues('Fixed prompt base logits')).toEqual(initial)
    open(/^Transformer block 1/); open(/^Multi-head causal attention/); open(/^Attention head 1/)
    fireEvent.click(screen.getByRole('button', { name: /^Attention weights row 1 column 2:/ }))
    click('Save state'); const saved = structuredClone(save.mock.calls.at(-1)![0])
    fireEvent.change(screen.getByRole('combobox', { name: 'Token at position 2' }), { target: { value: '3' } }); click('Run forward')
    fireEvent.change(screen.getByLabelText('Import exploration'), { target: { files: [{ text: async () => JSON.stringify(saved) }] } })
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('view restored'))
    expect(matrixValues('Fixed prompt base logits')).toEqual(initial)
    expect(screen.getByText('Query 1 → key 2')).toBeInTheDocument()
    click('Save state'); expect(save.mock.calls.at(-1)![0]).toEqual(saved)
  })
})
